### ISSUE TITLE
Minimizing window does not work

### ISSUE THREAD

**Issue by tschaefer** [bluemaex/bluemaex#1]
# Infos:
* Used bluemax version: Current
* Operating system: Any
* Browser + version: Any

# Expected behavior:
Mouse click on the arrow down button minimizes the window.

# Actual behavior:
Mouse click on the arrow down button does nothing.

# Steps to reproduce the behavior:
Click on the arrow down button with the mouse.
![screenshot-mark-minimize-button](https://user-images.githubusercontent.com/708717/203366477-a52518d7-2a25-45ed-8b4b-428ae43e802e.png)

**Comment by bluemaex** [comment]
❤️
